# -------------------------------
# MapProxy example configuration.
# -------------------------------
#
# This is a minimal MapProxy configuration.
# See full_example.yaml and the documentation for more options.
#

# Starts the following services:
# Demo:
#     http://localhost:8080/demo
# WMS:
#     capabilities: http://localhost:8080/service?REQUEST=GetCapabilities
# WMTS:
#     capabilities: http://localhost:8080/wmts/1.0.0/WMTSCapabilities.xml
#     first tile: http://localhost:8080/wmts/osm/webmercator/0/0/0.png
# Tile service (compatible with OSM/etc.)
#     first tile: http://localhost:8080/tiles/osm/webmercator/0/0/0.png
# TMS:
#     note: TMS is not compatible with OSM/Google Maps/etc.
#     fist tile: http://localhost:8080/tms/1.0.0/osm/webmercator/0/0/0.png
# KML:
#     initial doc: http://localhost:8080/kml/osm/webmercator

services:
  #sets up how to make the source data available
  demo:
  tms:
    use_grid_names: true
    origin: 'nw'
  wms:
    #srs sets the coordinate reference systems as which you want to make your data available. MapProxy reprojects the source data very well to these projections.
    srs: ['EPSG:900913', 'EPSG:3857']
    image_formats: ['image/jpeg', 'image/png']
    md:
      # metadata used in capabilities documents
      title: MapProxy WMS Proxy
      abstract: This is the fantastic MapProxy.
      online_resource: http://mapproxy.org/
      contact:
        person: Your Name
        position: Technical Director
        organization: Some Company
        address: Long street
        city: Timbuktu
        postcode: 123456AD
        country: South Pole
        email: info@example.com
      access_constraints:
        This service is intended for private and evaluation use only.
        The data is licensed as Creative Commons Attribution-Share Alike 2.0
        (http://creativecommons.org/licenses/by-sa/2.0/)
      fees: 'None'

layers:
  #sets up which layers you want to make available using the services above.
  - name: maaamet_orto
    title: Maaamet orto
    sources: [maaamet_cache]
  - name: osm
    title: Open Streetmap Tiles
    sources: [osm_cache] #this layer should use the osm_cache (defined below) as it's source.
  - name: osm_local
    title: Open Streetmap Tiles Local
    sources: [osm_local_cache]

caches:
  maaamet_cache_in:
    grids: [ee_grid]
    sources: [maaamet_ortofoto]
    disable_storage: true
    format: image/jpeg
    request_format: image/jpeg
  maaamet_cache:
    grids: [webmercator]
    sources: [maaamet_cache_in]
  #setup the cache for the open streetmap tiles. This cache is used by the layer above.
  osm_cache:
    sources: [osm_tiles] #here you set what source data (defined below) you want to cache
    format: image/png
  osm_local_cache:
    sources: [osm_local_tiles]
    format: image/png

sources:
  maaamet_ortofoto:
    #the maaamet_ortofoto source refers to the maamet.ee tiles. These will be downloaded upon request (if not already cached) and served by MapProxy
    type: tile
    url: http://tiles.maaamet.ee/tm/tms/1.0.0/foto/%(z)s/%(x)s/%(y)s.jpg
    grid: ee_grid
  osm_tiles:
    #the osm_tiles source refers to the openstreetmap.org tiles. These will be downloaded upon request (if not already cached) and served by MapProxy
    type: tile
    url: http://c.tile.openstreetmap.org/%(tms_path)s.%(format)s
    grid: osm_grid
  osm_local_tiles:
    type: tile
    url: http://openstreetmap/tile/%(z)s/%(x)s/%(y)s.png
    grid: osm_grid

grids:
  ee_grid:
    srs: 'EPSG:3301'
    bbox: [40500.000000, 5993000.000000, 1064500.000000, 7017000.000000]
    bbox_srs: 'EPSG:3301'
  webmercator:
    srs: 'EPSG:3857'
    origin: nw
    min_res: 156543.03392804097
  osm_grid:
    #this srs and origin specify a grid that can be used elsewhere in the configuration. In this example it is used for the osm_tiles source. These settings are correct for openstreetmap.org tiles.
    #The google mercator srs is used (also called EPSG:900913), and the origin of the tiles is north-west). If you get this wrong, you might very well get an all-blue world.
    srs: EPSG:900913
    origin: nw

globals:
  #next are some global configuration options for MapProxy. They mostly explain themselves, or can be looked-up in the MapProxy docs.
  cache:
    # where to store the cached images
    base_dir: './cache_data'
    # where to store lockfiles
    lock_dir: './cache_data/locks'

  # image/transformation options
  image:
    resampling_method: bilinear
    jpeg_quality: 90
